version: '3'
services:
   db:
      image: mysql:5.6
      ports:
       - "3306:3306"
      volumes:
       - D:\Projetos\data:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=admin
   rabbit:
      image: "rabbitmq:management"
      container_name: rabbitmq
      environment:
        RABBITMQ_DEFAULT_USER: "rabbitmq"
        RABBITMQ_DEFAULT_PASS: "rabbitmq"
      ports:
        - "15672:15672"
        - "5672:5672"